---
- hosts: local
  become: yes
  tasks:
    - name: Installing Docker
      command: >
        curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      tags: docker

    - name: Installing Vagrant
      become: yes
      apt:
        name: vagrant
        state: present
      tags: vagrant

    - name: Installing Terraform
      become: yes
      apt:
        name: unzip
        state: present
      tags: terraform
    - name: Downloading Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /tmp/terraform.zip
      tags: terraform
    - name: Extracting Terraform
      command: unzip /tmp/terraform.zip -d /usr/local/bin/
      tags: terraform
    - name: Cleaning up Terraform zip
      file:
        path: /tmp/terraform.zip
        state: absent
      tags: terraform

    - name: Installing VirtualBox
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
        state: present
        filename: oracle-virtualbox
        update_cache: yes
      tags: virtualbox
    - name: Adding VirtualBox repository key
      become: yes
      shell: wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
      tags: virtualbox
    - name: Updating package lists for VirtualBox
      become: yes
      apt:
        update_cache: yes
      tags: virtualbox
    - name: Installing VirtualBox
      become: yes
      apt:
        name: virtualbox
        state: present
      tags: virtualbox
    - name: Downloading VirtualBox Extension Pack
      get_url:
        url: https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack
        dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
      vars:
        virtualbox_version: "{{ query('command', 'VBoxManage --version | cut -d r -f 1') }}"
      tags: virtualbox
    - name: Installing VirtualBox Extension Pack
      become: yes
      shell: VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
      tags: virtualbox
    - name: Cleaning up VirtualBox Extension Pack
      become: yes
      file:
        path: /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
        state: absent
      tags: virtualbox

    - name: Installing kubectl
      become: yes
      apt:
        name: kubectl
        state: present
      tags: kubectl

    - name: Installing Minikube
      become: yes
      shell: >
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        && sudo install minikube-linux-amd64 /usr/local/bin/minikube
        && rm minikube-linux-amd64
      tags: minikube

    - name: Installing Kind
      become: yes
      shell: >
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        && chmod +x ./kind
        && sudo mv ./kind /usr/local/bin/
      tags: kind


    - name: Installing kubectx and kubens
      become: yes
      git:
        repo: https://github.com/ahmetb/kubectx.git
        dest: /opt/kubectx
        version: master
      tags: kubectx_kubens
    - name: Creating symlinks for kubectx and kubens
      become: yes
      file:
        src: /opt/kubectx/kubectx
        dest: /usr/local/bin/kubectx
        state: link
      tags: kubectx_kubens
    - name: Creating symlink for kubens
      become: yes
      file:
        src: /opt/kubectx/kubens
        dest: /usr/local/bin/kubens
        state: link
      tags: kubectx_kubens

    - name: Installing Google Cloud SDK
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main
        state: present
        update_cache: yes
        filename: google-cloud-sdk
      tags: google_cloud_sdk
    - name: Installing Google Cloud SDK package
      become: yes
      apt:
        name: google-cloud-sdk
        state: present
      tags: google_cloud_sdk

    - name: Installing Azure CLI
      become: yes
      shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      tags: azure_cli

    - name: Setting up kubectx and kubens
      become: yes
      git:
        repo: https://github.com/ahmetb/kubectx.git
        dest: ~/.kubectx
        version: master
      tags: kubectx_kubens
    - name: Creating symlinks for kubectx and kubens
      become: yes
      file:
        src: ~/.kubectx/completion/kubectx.bash
        dest: /etc/bash_completion.d/kubectx
        state: link
      tags: kubectx_kubens
    - name: Creating symlink for kubens
      become: yes
      file:
        src: ~/.kubectx/completion/kubens.bash
        dest: /etc/bash_completion.d/kubens
        state: link
      tags: kubectx_kubens

    - name: Installing Visual Studio Code
      become: yes
      apt_repository:
        repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
        state: present
        update_cache: yes
        filename: vscode
      tags: vscode
    - name: Installing Visual Studio Code package
      become: yes
      apt:
        name: code
        state: present
      tags: vscode

    - name: Installing GitHub Desktop
      become: yes
      get_url:
        url: https://github.com/shiftkey/desktop/releases/download/release-3.1.1-linux1/GitHubDesktop-linux-3.1.1-linux1.deb
        dest: /tmp/GitHubDesktop-linux-3.1.1-linux1.deb
      tags: github_desktop
    - name: Installing GitHub Desktop package
      become: yes
      apt:
        deb: /tmp/GitHubDesktop-linux-3.1.1-linux1.deb
        state: present
      tags: github_desktop
    - name: Cleaning up GitHub Desktop package
      become: yes
      file:
        path: /tmp/GitHubDesktop-linux-3.1.1-linux1.deb
        state: absent
      tags: github_desktop

    - name: Installing Python and pip
      become: yes
      apt:
        name: 
          - python3
          - python3-pip
        state: present
      tags: python

    - name: Installing pipx
      become: yes
      command: python3 -m pip install --user pipx
      tags: pipx
    - name: Ensuring pipx is in PATH
      become: yes
      command: python3 -m pipx ensurepath
      tags: pipx

    - name: Installing Ansible using pipx
      become: yes
      command: pipx install --include-deps ansible
      tags: ansible

    # - name: Rebooting the system
    #   become: yes
    #   command: reboot
    #   async: 0
    #   poll: 0
    #   ignore_errors: true
    #   changed_when: false
    #   tags: reboot

    # - name: Wait for system to come back up
    #   become: yes
    #   wait_for_connection:
    #     timeout: 300
    #   when: ansible_os_family == 'Debian'
    #   tags: reboot

    # - name: Wait for system to come back up
    #   become: yes
    #   wait_for:
    #     timeout: 300
    #     state: started
    #   when: ansible_os_family == 'RedHat'
    #   tags: reboot
